'use client';

import { useState } from 'react';
import { Wallet, PackageCheck, Clock, CheckCircle2 } from 'lucide-react';
import type { PayoutStatus } from 'shared-types';
import { PageHeader } from '@/components/shared/page-header';
import { LoadingBlock, ErrorBlock, EmptyState } from '@/components/shared/states';
import { NoStorePrompt } from '@/components/shared/no-store';
import { Pagination } from '@/components/shared/pagination';
import { StatCard } from '@/components/shared/stat-card';
import { Card } from '@/components/ui/card';
import { Select } from '@/components/ui/select';
import { PayoutStatusBadge } from '@/components/shared/status-badge';
import { useMyStore } from '@/features/store/hooks';
import { useMyPayouts, useEarnings } from '@/features/payouts/hooks';
import { formatPrice, formatDate } from '@/lib/utils';

const STATUS_FILTERS: (PayoutStatus | 'ALL')[] = [
  'ALL',
  'PENDING',
  'PROCESSING',
  'COMPLETED',
  'FAILED',
];

export default function PayoutsPage() {
  const { data: store, isLoading: storeLoading } = useMyStore();
  const { data: earnings } = useEarnings();
  const [page, setPage] = useState(1);
  const [status, setStatus] = useState<PayoutStatus | 'ALL'>('ALL');

  const { data, isLoading, isError } = useMyPayouts({
    page,
    status: status === 'ALL' ? undefined : status,
  });

  if (storeLoading) return <LoadingBlock />;
  if (!store) {
    return (
      <>
        <PageHeader title="Payouts" />
        <NoStorePrompt />
      </>
    );
  }

  const payouts = data?.items ?? [];

  return (
    <>
      <PageHeader
        title="Payouts"
        description="Your earnings from delivered orders and their disbursement status"
      />

      {earnings && (
        <div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <StatCard
            label="Delivered earnings"
            value={formatPrice(earnings.delivered.earnings)}
            icon={<PackageCheck className="h-5 w-5" />}
            hint={`${earnings.delivered.count} delivered order(s)`}
          />
          <StatCard
            label="Pending payout"
            value={formatPrice(earnings.payouts.pending)}
            icon={<Clock className="h-5 w-5" />}
          />
          <StatCard
            label="Processing"
            value={formatPrice(earnings.payouts.processing)}
            icon={<Wallet className="h-5 w-5" />}
          />
          <StatCard
            label="Paid out"
            value={formatPrice(earnings.payouts.completed)}
            icon={<CheckCircle2 className="h-5 w-5" />}
          />
        </div>
      )}

      <div className="mb-4 flex justify-end">
        <Select
          value={status}
          onChange={(e) => {
            setPage(1);
            setStatus(e.target.value as PayoutStatus | 'ALL');
          }}
          className="w-48"
        >
          {STATUS_FILTERS.map((s) => (
            <option key={s} value={s}>
              {s === 'ALL' ? 'All statuses' : s.charAt(0) + s.slice(1).toLowerCase()}
            </option>
          ))}
        </Select>
      </div>

      {isLoading && <LoadingBlock />}
      {isError && <ErrorBlock message="Could not load payouts." />}

      {data && payouts.length === 0 && (
        <EmptyState
          icon={<Wallet className="h-10 w-10" />}
          title="No payouts yet"
          description="Payouts are generated by admins once your orders are delivered. They'll show up here."
        />
      )}

      {payouts.length > 0 && (
        <Card className="overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="border-b border-border bg-muted/40 text-left text-xs uppercase text-muted-foreground">
                <tr>
                  <th className="px-4 py-3 font-medium">Payout</th>
                  <th className="px-4 py-3 font-medium">Amount</th>
                  <th className="px-4 py-3 font-medium">Status</th>
                  <th className="px-4 py-3 font-medium">Method</th>
                  <th className="px-4 py-3 font-medium">Reference</th>
                  <th className="px-4 py-3 font-medium">Date</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {payouts.map((p) => (
                  <tr key={p.id} className="hover:bg-muted/30">
                    <td className="px-4 py-3 font-mono text-xs text-muted-foreground">
                      #{p.id.slice(-8)}
                    </td>
                    <td className="px-4 py-3 font-medium">{formatPrice(p.amount)}</td>
                    <td className="px-4 py-3">
                      <PayoutStatusBadge status={p.status} />
                    </td>
                    <td className="px-4 py-3">{p.method ?? '—'}</td>
                    <td className="px-4 py-3">{p.reference ?? '—'}</td>
                    <td className="px-4 py-3 whitespace-nowrap text-muted-foreground">
                      {p.processedAt ? formatDate(p.processedAt) : formatDate(p.createdAt)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}

      <Pagination meta={data?.meta} page={page} onPageChange={setPage} />
    </>
  );
}
